### ISSUE TITLE
Search aborts from HowTo100m website

### ISSUE THREAD

**Issue by mdear** [antoine77340/howto100m#21]
The search at https://www.di.ens.fr/willow/research/howto100m/ errors out with the following error. Please fix. 

404 Not Found

Unexpected query string parameters: search

Traceback (most recent call last):
  File "/home/ROCQ/sed/praverdy/miniconda3/envs/howto100m/lib/python3.8/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
TypeError: index() got an unexpected keyword argument 'search'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ROCQ/sed/praverdy/miniconda3/envs/howto100m/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/home/ROCQ/sed/praverdy/miniconda3/envs/howto100m/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/home/ROCQ/sed/praverdy/miniconda3/envs/howto100m/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/ROCQ/sed/praverdy/miniconda3/envs/howto100m/lib/python3.8/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    raise sys.exc_info()[1]
  File "/home/ROCQ/sed/praverdy/miniconda3/envs/howto100m/lib/python3.8/site-packages/cherrypy/_cpdispatch.py", line 58, in __call__
    test_callable_spec(self.callable, self.args, self.kwargs)
  File "/home/ROCQ/sed/praverdy/miniconda3/envs/howto100m/lib/python3.8/site-packages/cherrypy/_cpdispatch.py", line 191, in test_callable_spec
    raise cherrypy.HTTPError(404, message=message)
cherrypy._cperror.HTTPError: (404, 'Unexpected query string parameters: search')
Powered by CherryPy unknown

**Comment by study-overflow** [comment]
Same question.
